fighting cygwin, can't load script from git

diff --git a/templates/default/scala-release-2.11.x-windows.xml.erb b/templates/default/scala-release-2.11.x-windows.xml.erb
--- a/templates/default/scala-release-2.11.x-windows.xml.erb
+++ b/templates/default/scala-release-2.11.x-windows.xml.erb
@@ -96,17 +96,44 @@ The downloads will be available at http://downloads.typesafe.com/scala/$ver/scal
   <concurrentBuild>true</concurrentBuild>
   <builders>
     <hudson.tasks.Shell>
-      <command>#!"C:\Program Files (x86)\git\bin\bash.exe" -ex
+      <command> <!-- having trouble with line-endings and git, so copy/pasted for now -->
+#!C:/cygwin64/bin/bash -ex
 
-# the standard way of getting the jenkins-scripts directory -- do not change!
-if [[ -d jenkins-scripts ]]; then
-  ( cd jenkins-scripts &amp;&amp; git fetch $scriptsRemote HEAD &amp;&amp; git checkout -f FETCH_HEAD &amp;&amp; git clean -fxd )
-else
-  git clone $scriptsRemote
+#TODO: move PATH to slave config
+export PATH="/usr/bin:/bin:$(/usr/bin/cygpath --unix $JAVA_HOME)/bin"
+
+WORKSPACE=`/usr/bin/cygpath --unix $WORKSPACE`
+
+# no bang here, because we want to run both under cygwin and real unix
+# sbtDistTarget must be supplied
+# sbtDistVersionOverride may be -Dproject.version=....  to override the version of the dist to build (only for testing, you should use tags for real releases!)
+# sbtLauncher is a global jenkins configuration variable
+repositoriesFile="$WORKSPACE/jenkins-scripts/repositories-scala-release"
+
+echo "Using repo config:"
+cat "$repositoriesFile"
+
+# version is set by the scala-release-2.11.x-dist build flow, make sure it's consistent with the tag
+# this is also a backstop for https://github.com/sbt/sbt-git/issues/35
+# ignore when there is no version (job is running outside of the flow)
+
+# http://stackoverflow.com/questions/4545370/how-to-list-all-tags-pointing-to-a-specific-commit-in-git
+# if only we had git 1.7.10 or higher: tags="$(git tag --points-at HEAD)"
+tags="$(git show-ref --tags -d | grep $(git rev-parse HEAD) | cut -f3 -d/ | cut -f1 -d^)"
+
+[[ -z $sbtDistVersionOverride ]] && [[ -n $version ]] && if [ "$tags" != "v$version" ]; then
+  echo "Inconsistent tag/version combo detected. Abort-abort."
+  exit 255
 fi
-# done getting jenkins-scripts
 
-. ./jenkins-scripts/job/scala-release-2.11.x-dist
+rm -rf $WORKSPACE/.ivy2
+
+# want full control over sbt, so invoke the launcher directly
+java -Dsbt.log.noformat=true -Dsbt.ivy.home=$WORKSPACE/.ivy2 \
+  -Dsbt.override.build.repos=true -Dsbt.repository.config="$repositoriesFile" \
+  -jar $sbtLauncher \
+  $sbtDistVersionOverride \
+  clean update $sbtDistTarget
 </command>
     </hudson.tasks.Shell>
   </builders>
